name: product_stock_management_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  dartz: ^0.10.1
  flutter_svg: ^2.0.17
  top_snackbar_flutter: ^3.1.0
  intl: ^0.19.0
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.3
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translation/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 600
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 500
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
